# Generated by Django 3.1.1 on 2020-09-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('country', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('emails', models.TextField()),
                ('embeded', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
