# Generated by Django 3.1.1 on 2020-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200926_0455'),
    ]

    operations = [


    ]
