# Generated by Django 3.1.1 on 2020-09-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200926_1710'),
    ]

    operations = [

    ]
