# Generated by Django 3.1.1 on 2020-10-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201004_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
