# Generated by Django 3.1.1 on 2020-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_tests_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='duration',
        ),
    ]
