# Generated by Django 3.1.1 on 2020-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_tests_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='auto_test_creation',
            field=models.BooleanField(default=False),
        ),
    ]
