# Generated by Django 3.1.1 on 2020-10-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_events_auto_test_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='topic',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
