# Generated by Django 3.1.1 on 2020-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201013_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
